apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: {{ prefix-name }}-{{ suffix-name }}
  labels:
    p6m.dev/app: {{ prefix-name }}-{{ suffix-name }}
spec:
  config:
    GRPC_PORT: "8080"
    SERVER_PORT: "8081"
    LOGGING_STRUCTURED: "true"
  deployment:
    image: {{ prefix-name }}-{{ suffix-name }}-server:latest
    ports:
      - protocol: grpc
        port: 8080
      - protocol: http
        port: 8081
    readinessProbe:
      port: 8081
      path: /health

  networking:
    inbound:
      services:
        - name: {{ prefix-name }}-{{ suffix-name }}
          namespace: {{ prefix-name }}-{{ suffix-name }}
          port: 8080
